spring:
  application:
    name: test-admin-server

server:
  port: 8769

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/